#!/bin/bash

echo "$@"

$@ && break | echo $?

option="empty"
while [ ! $option = "exit" ]; do
	read option
	case $option in
		ls) ls . ;;
		pwd) pwd;;
		hi) echo "Hi $(echo ~)";;
		*) ;;
	esac
done
#Test line 1
#Test line 2
#Test line 3
